Repository oceanprotocol/contracts, pull requests merged in 2022-01, with the labels that each got.

#448 Vesting issues
  addresses/address.json
  artifacts/contracts/interfaces/IFactoryRouter.sol/IFactoryRouter.json
  artifacts/contracts/pools/FactoryRouter.sol/FactoryRouter.json
  artifacts/contracts/pools/ssContracts/SideStaking.sol/SideStaking.json
  artifacts/contracts/templates/ERC20Template.sol/ERC20Template.json
  contracts/interfaces/IFactoryRouter.sol
  contracts/pools/FactoryRouter.sol
  contracts/pools/ssContracts/SideStaking.sol
  contracts/templates/ERC20Template.sol
  test/flow/SwapFees.test.js
  test/flow/Vesting.test.js
Labels: Status: DoNotMerge

#449 fix vesting
  addresses/address.json
  artifacts/contracts/pools/ssContracts/SideStaking.sol/SideStaking.json
  contracts/pools/ssContracts/SideStaking.sol
  test/flow/SideStaking.test.js
  test/flow/SwapBatch.test.js
  test/flow/SwapFees.test.js
Labels: Status: DoNotMerge

#469 fix #450
  artifacts/contracts/communityFee/OPFCommunityFeeCollector.sol/OPFCommunityFeeCollector.json
  artifacts/contracts/interfaces/IFixedRateExchange.sol/IFixedRateExchange.json
  artifacts/contracts/interfaces/IPool.sol/IPool.json
  artifacts/contracts/interfaces/ISideStaking.sol/ISideStaking.json
  artifacts/contracts/pools/FactoryRouter.sol/FactoryRouter.json
  artifacts/contracts/pools/balancer/BPool.sol/BPool.json
  artifacts/contracts/pools/fixedRate/FixedRateExchange.sol/FixedRateExchange.json
  artifacts/contracts/pools/ssContracts/SideStaking.sol/SideStaking.json
  artifacts/contracts/templates/ERC20Template.sol/ERC20Template.json
  artifacts/contracts/templates/ERC20TemplateEnterprise.sol/ERC20TemplateEnterprise.json
  contracts/ERC721Factory.sol
  contracts/communityFee/OPFCommunityFeeCollector.sol
  contracts/interfaces/IFactoryRouter.sol
  contracts/interfaces/IFixedRateExchange.sol
  contracts/interfaces/IPool.sol
  contracts/interfaces/ISideStaking.sol
  contracts/interfaces/IV3Factory.sol
  contracts/pools/FactoryRouter.sol
  contracts/pools/balancer/BFactory.sol
  contracts/pools/balancer/BMath.sol
  contracts/pools/balancer/BPool.sol
  contracts/pools/dispenser/Dispenser.sol
  contracts/pools/fixedRate/FixedRateExchange.sol
  contracts/pools/ssContracts/SideStaking.sol
  contracts/templates/ERC20Template.sol
  contracts/templates/ERC20TemplateEnterprise.sol
  contracts/templates/ERC721Template.sol
  contracts/utils/mock/MockOldDT.sol
  test/flow/Dispenser.test.js
  test/flow/FixedRateExchange.test.js
  test/flow/SideStaking.test.js
  test/flow/SwapBatch.test.js
  test/flow/SwapFees.test.js
  test/flow/Vesting.test.js
  test/unit/datatokens/ERC20TemplateEnterprise.test.js
  test/unit/factories/ERC721Factory.test.js
Labels: Status: DoNotMerge, Breaking changes

#471 proper baseToken namings
  artifacts/contracts/interfaces/IFixedRateExchange.sol/IFixedRateExchange.json
  artifacts/contracts/interfaces/IPool.sol/IPool.json
  artifacts/contracts/interfaces/ISideStaking.sol/ISideStaking.json
  artifacts/contracts/pools/balancer/BPool.sol/BPool.json
  artifacts/contracts/pools/fixedRate/FixedRateExchange.sol/FixedRateExchange.json
  artifacts/contracts/pools/ssContracts/SideStaking.sol/SideStaking.json
  artifacts/contracts/templates/ERC20TemplateEnterprise.sol/ERC20TemplateEnterprise.json
  contracts/interfaces/IFixedRateExchange.sol
  contracts/interfaces/IPool.sol
  contracts/interfaces/ISideStaking.sol
  contracts/pools/balancer/BPool.sol
  contracts/pools/fixedRate/FixedRateExchange.sol
  contracts/pools/ssContracts/SideStaking.sol
  contracts/templates/ERC20TemplateEnterprise.sol
  test/flow/SideStaking.test.js
  test/unit/datatokens/ERC20TemplateEnterprise.test.js
Labels: Breaking changes

#470 split orders & fees
  artifacts/contracts/ERC721Factory.sol/ERC721Factory.json
  artifacts/contracts/interfaces/IERC20Template.sol/IERC20Template.json
  artifacts/contracts/templates/ERC20Template.sol/ERC20Template.json
  artifacts/contracts/templates/ERC20TemplateEnterprise.sol/ERC20TemplateEnterprise.json
  artifacts/contracts/templates/ERC721Template.sol/ERC721Template.json
  contracts/ERC721Factory.sol
  contracts/interfaces/IERC20Template.sol
  contracts/templates/ERC20Template.sol
  contracts/templates/ERC20TemplateEnterprise.sol
  test/unit/datatokens/ERC20Template.test.js
  test/unit/datatokens/ERC20TemplateEnterprise.test.js
  test/unit/factories/ERC721Factory.test.js
Labels: Breaking changes

#480 dynamic OPC fees
  .bumpversion.cfg
  .github/workflows/ci.yml
  .github/workflows/npm-publish.yml
  .github/workflows/python-publish.yml
  addresses/address.json
  artifacts/contracts/interfaces/IFactoryRouter.sol/IFactoryRouter.json
  artifacts/contracts/interfaces/IFixedRateExchange.sol/IFixedRateExchange.json
  artifacts/contracts/interfaces/IMetadata.sol/IMetadata.json
  artifacts/contracts/pools/FactoryRouter.sol/FactoryRouter.json
  artifacts/contracts/pools/balancer/BFactory.sol/BFactory.json
  artifacts/contracts/pools/balancer/BMath.sol/BMath.json
  artifacts/contracts/pools/balancer/BPool.sol/BPool.json
  artifacts/contracts/pools/fixedRate/FixedRateExchange.sol/FixedRateExchange.json
  artifacts/contracts/templates/ERC20Template.sol/ERC20Template.json
  artifacts/contracts/templates/ERC20TemplateEnterprise.sol/ERC20TemplateEnterprise.json
  artifacts/contracts/utils/ERC721/Strings.sol/Strings.json
  artifacts/contracts/utils/ERC721RolesAddress.sol/ERC721RolesAddress.json
  artifacts/contracts/utils/SafeERC20.sol/SafeERC20.json
  artifacts/contracts/utils/mock/MockERC20.sol/MockERC20.json
  artifacts/contracts/utils/mock/MockERC20Decimals.sol/MockERC20Decimals.json
  artifacts/contracts/utils/mock/MockExchange.sol/MockExchange.json
  artifacts/contracts/utils/mock/MockOcean.sol/MockOcean.json
  artifacts/contracts/utils/mock/MockOldDT.sol/MockOldDT.json
  artifacts/contracts/v3/V3DTFactory.sol/V3DTFactory.json
  artifacts/contracts/v3/V3DataTokenTemplate.sol/V3DataTokenTemplate.json
  artifacts/contracts/v3/V3MetaData.sol/V3Metadata.json
  contracts/interfaces/IFactoryRouter.sol
  contracts/interfaces/IFixedRateExchange.sol
  contracts/pools/FactoryRouter.sol
  contracts/pools/balancer/BFactory.sol
  contracts/pools/balancer/BMath.sol
  contracts/pools/balancer/BPool.sol
  contracts/pools/fixedRate/FixedRateExchange.sol
  contracts/templates/ERC20Template.sol
  contracts/templates/ERC20TemplateEnterprise.sol
  hardhat.config.js
  package.json
  scripts/deploy_docker.sh
  setup.cfg
  test/flow/Dispenser.test.js
  test/flow/FixedRateExchange.test.js
  test/flow/NFTCreation.test.js
  test/flow/SideStaking.test.js
  test/flow/SwapBatch.test.js
  test/flow/SwapFees.test.js
  test/flow/Vesting.test.js
  test/unit/datatokens/ERC20Template.test.js
  test/unit/datatokens/ERC20TemplateEnterprise.test.js
  test/unit/datatokens/ERC721Template.test.js
  test/unit/factories/ERC721Factory.test.js
  test/unit/pools/FactoryRouter.test.js
Labels: Status: DoNotMerge
